---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен иметь функциональность управления пользователями (регистрация, авторизация).
  - Производители должны быть проранжированы по алфавиту.
  - Пользователь должен иметь возможность при добавлении товара в корзину изменить количесво товара на необходимое.
  - Пользователь должен иметь возможность изменять количество товара в корзине на необходимое.
  - Пользователь должен иметь возможность после выбора категории очистить это поле без обновления страницы.
  - При смене языка должен осуществляться перевод кнопок, полей и содержание полей.
  - В информации о товаре пользователь должен видеть количество данного товара на складе.
  - Пользователь должен иметь возможность отфильтровать товары по наличию.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Пользователь должен иметь возможность оформить товар на сайте
